

all : asmimportusingld.dll

asmimportusingld.dll : asmimportusingld.dglu FORCE
	..\..\diaperglu asmimportusingld.dglu

.PHONY: FORCE
FORCE:

.PHONY : superclean
superclean :
	del asmexportonlyusingld.dll asmexportonlyusingld.exp asmexportonlyusingld.lib asmexportonlyusingld.obj asmexportonlyusingld.dll asmimportusingld.dll asmimportusingld.exp asmimportusingld.lib asmimportusingld.obj



	


