
.PHONY: all
all : libasmimportusingld.dylib

libasmimportusingld.dylib : asmimportusingld.dglu FORCE
	../../diaperglu asmimportusingld.dglu

.PHONY: FORCE
FORCE:

superclean : FORCE
	rm libasmexportonlyusingld.dylib libasmimportusingld.dylib



	


